export type Word = { kanji: string; yomi: string; wrong: string };

// 漢検2級レベルの熟語（正解の読み / もっともらしい誤答）
export const WORDS: Word[] = [
  { kanji: "憂鬱", yomi: "ゆううつ", wrong: "ゆうしゅう" },
  { kanji: "賄賂", yomi: "わいろ", wrong: "まいろ" },
  { kanji: "漠然", yomi: "ばくぜん", wrong: "もうぜん" },
  { kanji: "稚拙", yomi: "ちせつ", wrong: "ちさつ" },
  { kanji: "遡及", yomi: "そきゅう", wrong: "さくきゅう" },
  { kanji: "払拭", yomi: "ふっしょく", wrong: "ふっしき" },
  { kanji: "軌跡", yomi: "きせき", wrong: "きぜき" },
  { kanji: "斬新", yomi: "ざんしん", wrong: "せんしん" },
  { kanji: "頒布", yomi: "はんぷ", wrong: "ぶんぷ" },
  { kanji: "懸念", yomi: "けねん", wrong: "けんねん" },
  { kanji: "凡例", yomi: "はんれい", wrong: "ぼんれい" },
  { kanji: "妥協", yomi: "だきょう", wrong: "たきょう" },
  { kanji: "示唆", yomi: "しさ", wrong: "じさ" },
  { kanji: "旺盛", yomi: "おうせい", wrong: "ほうせい" },
  { kanji: "把握", yomi: "はあく", wrong: "ひあく" },
  { kanji: "顕著", yomi: "けんちょ", wrong: "げんちょ" },
  { kanji: "脚色", yomi: "きゃくしょく", wrong: "あしいろ" },
  { kanji: "拘泥", yomi: "こうでい", wrong: "くでい" },
  { kanji: "洗浄", yomi: "せんじょう", wrong: "せんてい" },
  { kanji: "弾劾", yomi: "だんがい", wrong: "だんがく" },
  { kanji: "嗜好", yomi: "しこう", wrong: "じこう" },
  { kanji: "捻出", yomi: "ねんしゅつ", wrong: "ちんしゅつ" },
  { kanji: "雰囲気", yomi: "ふんいき", wrong: "ふいんき" },
  { kanji: "若干", yomi: "じゃっかん", wrong: "わかかん" },
  { kanji: "為替", yomi: "かわせ", wrong: "ためかえ" },
  { kanji: "貪欲", yomi: "どんよく", wrong: "とんよく" },
  { kanji: "出納", yomi: "すいとう", wrong: "しゅつのう" },
  { kanji: "境内", yomi: "けいだい", wrong: "きょうない" },
  { kanji: "建立", yomi: "こんりゅう", wrong: "けんりつ" },
  { kanji: "吐露", yomi: "とろ", wrong: "はろ" },
  { kanji: "趣旨", yomi: "しゅし", wrong: "しゅうし" },
  { kanji: "添削", yomi: "てんさく", wrong: "てんしょう" },
  { kanji: "更迭", yomi: "こうてつ", wrong: "こうしょう" },
  { kanji: "渋滞", yomi: "じゅうたい", wrong: "しぶたい" },
  { kanji: "誘拐", yomi: "ゆうかい", wrong: "ゆうかん" },
  { kanji: "傲慢", yomi: "ごうまん", wrong: "きょうまん" },
  { kanji: "懐柔", yomi: "かいじゅう", wrong: "かいにゅう" },
  { kanji: "紛糾", yomi: "ふんきゅう", wrong: "ふんりゅう" },
  { kanji: "漸進", yomi: "ぜんしん", wrong: "ざんしん" },
  { kanji: "蔓延", yomi: "まんえん", wrong: "ばんえん" },
  { kanji: "暫定", yomi: "ざんてい", wrong: "ぜんてい" },
  { kanji: "抜粋", yomi: "ばっすい", wrong: "ばっさい" },
  { kanji: "拙速", yomi: "せっそく", wrong: "ざっそく" },
  { kanji: "淘汰", yomi: "とうた", wrong: "とうしょく" },
  { kanji: "該当", yomi: "がいとう", wrong: "かいとう" },
  { kanji: "享受", yomi: "きょうじゅ", wrong: "こうじゅ" },
  { kanji: "恣意", yomi: "しい", wrong: "じい" },
  { kanji: "隠蔽", yomi: "いんぺい", wrong: "おんぺい" },
  { kanji: "席巻", yomi: "せっけん", wrong: "せきかん" },
  { kanji: "破綻", yomi: "はたん", wrong: "はてい" },
];
